### ISSUE TITLE
Error: when run sample-queries-tpcds/query1.sql

### ISSUE THREAD

**Issue by godtree** [hortonworks/hive-testbench#21]
CDH  6.0.0    Hive  2.1.1
when run the script hive-testbench/sample-queries-tpcds/query1.sql, it show the error:

source query1.sql;
FAILED: ParseException line 15:31 cannot recognize input near '(' 'select' 'avg' in expression specification

and query2.sql do not work, too.

**Comment by godtree** [comment]
But the query3.sql and query55.sql are ok.

**Comment by godtree** [comment]
hive> source query1.sql;
NoViableAltException(258@[392:1: atomExpression : ( ( KW_NULL )=> KW_NULL -> TOK_NULL | ( intervalExpression )=> intervalExpression | ( constant )=> constant | castExpression | extractExpression | floorExpression | caseExpression | whenExpression | ( functionName LPAREN )=> function | tableOrColumn | LPAREN ! expression RPAREN !);])
	at org.antlr.runtime.DFA.noViableAlt(DFA.java:158)
	at org.antlr.runtime.DFA.predict(DFA.java:116)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.atomExpression(HiveParser_IdentifiersParser.java:6407)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceFieldExpression(HiveParser_IdentifiersParser.java:6636)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceUnaryPrefixExpression(HiveParser_IdentifiersParser.java:6972)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceUnarySuffixExpression(HiveParser_IdentifiersParser.java:7028)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceBitwiseXorExpression(HiveParser_IdentifiersParser.java:7190)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceStarExpression(HiveParser_IdentifiersParser.java:7333)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedencePlusExpression(HiveParser_IdentifiersParser.java:7476)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceConcatenateExpression(HiveParser_IdentifiersParser.java:7615)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceAmpersandExpression(HiveParser_IdentifiersParser.java:7825)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceBitwiseOrExpression(HiveParser_IdentifiersParser.java:7966)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceEqualExpressionSingle(HiveParser_IdentifiersParser.java:8627)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceEqualExpression(HiveParser_IdentifiersParser.java:8408)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceNotExpression(HiveParser_IdentifiersParser.java:9854)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceAndExpression(HiveParser_IdentifiersParser.java:9963)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.precedenceOrExpression(HiveParser_IdentifiersParser.java:10104)
	at org.apache.hadoop.hive.ql.parse.HiveParser_IdentifiersParser.expression(HiveParser_IdentifiersParser.java:6342)
	at org.apache.hadoop.hive.ql.parse.HiveParser.expression(HiveParser.java:39707)
	at org.apache.hadoop.hive.ql.parse.HiveParser_FromClauseParser.searchCondition(HiveParser_FromClauseParser.java:5224)
	at org.apache.hadoop.hive.ql.parse.HiveParser_FromClauseParser.whereClause(HiveParser_FromClauseParser.java:5142)
	at org.apache.hadoop.hive.ql.parse.HiveParser.whereClause(HiveParser.java:39653)
	at org.apache.hadoop.hive.ql.parse.HiveParser.selectStatement(HiveParser.java:34917)
	at org.apache.hadoop.hive.ql.parse.HiveParser.regularBody(HiveParser.java:34803)
	at org.apache.hadoop.hive.ql.parse.HiveParser.queryStatementExpressionBody(HiveParser.java:33992)
	at org.apache.hadoop.hive.ql.parse.HiveParser.queryStatementExpression(HiveParser.java:33880)
	at org.apache.hadoop.hive.ql.parse.HiveParser.execStatement(HiveParser.java:2205)
	at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1313)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:208)
	at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:75)
	at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:68)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:525)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1347)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1480)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1267)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1257)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:239)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:187)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:409)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:342)
	at org.apache.hadoop.hive.cli.CliDriver.processReader(CliDriver.java:489)
	at org.apache.hadoop.hive.cli.CliDriver.processFile(CliDriver.java:505)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:153)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:409)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:838)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:774)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:701)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:313)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:227)
FAILED: ParseException line 15:31 cannot recognize input near '(' 'select' 'avg' in expression specification
