### ISSUE TITLE
testbench.settings file not found

### ISSUE THREAD

**Issue by dgaikwad** [hortonworks/hive-testbench#3]
Hi,
 I am trying to run this benchmark on my setup but while running sample query current repository unable to find "testbench.settings" file on bellow location
```root@sn1:/bench/hive-testbench/sample-queries-tpcds# hive -i testbench.settings

Logging initialized using configuration in jar:file:/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/jars/hive-common-1.1.0-cdh5.14.2.jar!/hive-log4j.properties
WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.
Exception in thread "main" java.io.FileNotFoundException: File file:/bench/hive-testbench/sample-queries-tpcds/testbench.settings does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:598)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:811)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:588)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:432)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:142)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:344)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:784)
	at org.apache.hadoop.hive.cli.CliDriver.processFile(CliDriver.java:437)
	at org.apache.hadoop.hive.cli.CliDriver.processInitFiles(CliDriver.java:449)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:723)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:699)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:634)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
root@sn1:/bench/hive-testbench/sample-queries-tpcds# ls /bench/hive-testbench/sample-queries-tpcds/testbench.settings 
ls: cannot access /bench/hive-testbench/sample-queries-tpcds/testbench.settings: No such file or directory
root@sn1:/bench/hive-testbench/sample-queries-tpcds# 
```

**Comment by mave89** [comment]
I used the one from "sample-queries-tpch" folder.
