### ISSUE TITLE
SQL parsing errors (HDP 2.6)

### ISSUE THREAD

**Issue by yuliu-sn** [hortonworks/hive-testbench#7]
Got many parsing errors when executing benchmarks on both TPC-DS and TPC-H.
However, the same sql can be parsed and executed via the UI of Hive View 2.

Platform: HDP 2.6, Hive +LLAP 
Error messages:
`NoViableAltException(26@[])
	at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1114)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:211)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:171)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:447)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:330)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1233)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1274)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1170)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1160)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:217)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:169)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:380)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:740)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:685)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:625)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:233)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)`

**Comment by yuliu-sn** [comment]
The branch of Hive-Testbench I used was "hdp3". Also tried hdp26 but got the same results.

**Comment by yuliu-sn** [comment]
It is resolved by setting the hive2 JDBC string. It just doesn't work with the by-default setting.
